{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
  type: {{ .type }}
  ports:
  {{- range $index, $port := .ports }}
  - port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: {{ $port.protocol }}
    name: {{ $port.name }}
  {{- end }}
  selector:
    app: {{ $.Release.Name }}
{{- end }}
